[build]
command = "NODE_VERSION=20.0.0 npm install --force && npm run build"
pages_build_output_dir = "out"

[site]
bucket = "./out"

[env.production]
node_version = "20.0.0"

[build.environment]
NODE_VERSION = "20.0.0"
NODE_ENV = "production" 