name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  NODE_ENV: production
  NEXT_PUBLIC_BASE_PATH: /ai-research-sc
  NEXT_TELEMETRY_DISABLED: 1

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18.17.0"
          cache: 'npm'

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          # Try npm ci first, fall back to npm install if it fails
          npm ci || npm install
          echo "Verifying critical dependencies..."
          npm list tailwindcss postcss autoprefixer
          echo "Checking node_modules..."
          ls -la node_modules/tailwindcss
          ls -la node_modules/postcss
          ls -la node_modules/autoprefixer
          echo "Checking configurations..."
          cat tailwind.config.js
          cat postcss.config.js

      - name: Build with Next.js
        run: |
          echo "Starting build process..."
          NODE_ENV=production npm run build
          touch out/.nojekyll
        env:
          CI: true
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: 1
          NEXT_PUBLIC_BASE_PATH: /ai-research-sc

      - name: Verify build output
        run: |
          echo "Checking build output..."
          ls -la out/
          echo "Checking for CSS files..."
          find out/ -name "*.css"
          echo "Checking for JS files..."
          find out/ -name "*.js"
          echo "Checking for HTML files..."
          find out/ -name "*.html"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 