name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  NODE_ENV: production
  NEXT_PUBLIC_BASE_PATH: /ai-research-sc-analytics

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0
          
      - name: Git LFS Pull
        run: git lfs pull
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm install --no-package-lock
          npm install --save-exact @react-pdf/renderer@3.1.14 dequal@2.0.3 pdfjs-dist@3.11.174 react-pdf@7.3.3 warning@4.0.3
          npm install --save-dev --save-exact tailwindcss@3.3.0 postcss@8.4.32 autoprefixer@10.4.16
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Build
        run: |
          npm run build
          touch out/.nojekyll
          cp -r public/* out/
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 