name: Deploy Next.js site to Pages

# Deployment trigger: Manual re-run
on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  NODE_ENV: production
  NEXT_PUBLIC_BASE_PATH: /ai-research-sc-analytics

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18.17.0"
          cache: 'npm'

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      # Clean install dependencies
      - name: Clean install
        run: |
          echo "Cleaning node_modules and package-lock.json..."
          rm -rf node_modules package-lock.json
          echo "Installing dependencies..."
          npm install --no-audit
          echo "Installing Tailwind CSS and related packages..."
          npm install tailwindcss@3.3.0 postcss@8.4.32 autoprefixer@10.4.16 --save-exact
          echo "Verifying installations..."
          npm list tailwindcss postcss autoprefixer

      # Verify project structure
      - name: Verify project structure
        run: |
          echo "Checking critical files..."
          ls -la
          echo "Checking Tailwind config..."
          cat tailwind.config.js
          echo "Checking PostCSS config..."
          cat postcss.config.js
          echo "Node modules contents..."
          ls -la node_modules/tailwindcss
          ls -la node_modules/postcss
          ls -la node_modules/autoprefixer

      - name: Build with Next.js
        run: |
          echo "Starting Next.js build..."
          npm run build
          touch out/.nojekyll
        env:
          CI: true
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: 1
          NEXT_PUBLIC_BASE_PATH: /ai-research-sc-analytics

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 