name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Important: Allow write to the gh-pages branch
permissions:
  contents: write
  pages: write
  id-token: write

# Force a fresh deployment every time
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0
          
      - name: Git LFS Pull
        run: git lfs pull
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'
          
      - name: Clean and Install
        run: |
          echo "Starting clean installation at $(date)"
          rm -rf .git/index.lock
          git clean -fdx
          npm cache clean --force
          rm -rf node_modules
          rm -rf .next
          rm -rf out
          npm ci --legacy-peer-deps
          echo "Installation completed at $(date)"
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Build
        run: |
          echo "Build started at $(date)"
          NODE_ENV=production npm run build
          echo "Build completed at $(date)"
        env:
          NODE_ENV: production
          NEXT_PUBLIC_BASE_PATH: /ai-research-sc-analytics
          CI: false

      - name: Prepare static files
        run: |
          echo "Preparing static files at $(date)"
          touch out/.nojekyll
          cp -r public/* out/
          echo "Deployment build info:" > out/build-info.txt
          echo "Built at: $(date)" >> out/build-info.txt
          echo "Commit: ${{ github.sha }}" >> out/build-info.txt
          echo "Branch: ${{ github.ref }}" >> out/build-info.txt
          echo "Deployment timestamp: $(date +%s)" >> out/build-info.txt
          
      - name: Verify output directory
        run: |
          echo "Verifying output at $(date)"
          echo "Contents of out directory:"
          ls -la out/
          echo "Contents of out/images directory:"
          ls -la out/images/
          echo "Contents of out/media directory:"
          ls -la out/media/
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 